name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Add a new trigger for the workflow_dispatch event

jobs:
  build:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }} # Conditionally run the job based on the event type

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2          

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create "staging" directory if it doesn't exist
      run: mkdir -p staging
      
    - name: Store JAR in "staging" directory
      run: cp target/*.jar staging/      
